Repository Harmari/FE, pull requests merged in 2025-02, with the labels that each got.

#13 feat: 디자이너 목록 기능 구현 및 환경 설정
  db.json
  package-lock.json
  package.json
  src/apis/designerList.ts
  src/apis/endpoints.js
  src/apis/endpoints.ts
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/constants/queryKey.ts
  src/main.tsx
  src/pages/DesignerListPage/components/DesignerItem.tsx
  src/pages/DesignerListPage/components/DesignerList.tsx
  src/pages/DesignerListPage/index.tsx
  src/pages/index.ts
  src/routes/route/DESIGNER_LIST.tsx
  src/routes/route/index.ts
  src/routes/router.tsx
  src/types/apiTypes.ts
  src/types/types.ts
Labels: feature

#44 feat: 디자이너 리스트 필터 기능 구현 및 ui 개선
  package-lock.json
  package.json
  src/apis/designerList.ts
  src/constants/queryKey.ts
  src/pages/DesignerListPage/components/DesignerFilter/DesignerFilterDrawer.tsx
  src/pages/DesignerListPage/components/DesignerFilter/FilterDrawer.tsx
  src/pages/DesignerListPage/components/DesignerFilter/FilteredOptionBox.tsx
  src/pages/DesignerListPage/components/DesignerList/DesignerItem.tsx
  src/pages/DesignerListPage/components/DesignerList/DesignerList.tsx
  src/pages/DesignerListPage/components/ReservationItem.tsx
  src/pages/DesignerListPage/components/filteredOptionbox.tsx
  src/pages/DesignerListPage/index.tsx
  src/types/types.ts
  src/utils/filterOption.ts
Labels: feature

#49 feat: 디자이너 날짜 및 시간 선택 기능
  public/images/goToBack-icon.svg
  public/images/heart-icon.svg
  public/images/home-icon.svg
  public/images/pointer-icon.svg
  src/apis/endpoints.ts
  src/apis/reservation.ts
  src/constants/path.ts
  src/pages/DesignerDetailPage/components/DesignerDetail.tsx
  src/pages/DesignerDetailPage/components/DesignerDetailHeader.tsx
  src/pages/DesignerDetailPage/index.tsx
  src/pages/DesignerListPage/components/DesignerList/DesignerItem.tsx
  src/pages/DesignerListPage/components/DesignerList/DesignerList.tsx
  src/pages/ReservationPage/components/ReservationSection.tsx
  src/pages/ReservationPage/index.tsx
  src/pages/ReservationPrepare/index.tsx
  src/pages/index.ts
  src/routes/route/DESIGNER_ROUTES.tsx
  src/routes/route/PAYMENTS_ROUTES.tsx
  src/types/apiTypes.ts
  src/types/types.ts
Labels: feature

#52 디자이너 필터 옵션에 가격 추가 및 디자인 수정
  src/apis/designerList.ts
  src/components/common/Footer.tsx
  src/hooks/useDebounce.tsx
  src/pages/DesignerDetailPage/components/DesignerDetail.tsx
  src/pages/DesignerListPage/components/DesignerFilter/DesignerFilterDrawer.tsx
  src/pages/DesignerListPage/components/DesignerFilter/FilterDrawer.tsx
  src/types/types.ts
  tailwind.config.ts
Labels: feature

#63 디자이너 필터 리팩토링 및 UI/UX 개선
  package-lock.json
  package.json
  src/App.tsx
  src/apis/designerList.ts
  src/components/ui/calendar.tsx
  src/components/ui/slider.tsx
  src/hooks/useAxiosInterceptor.tsx
  src/pages/DesignerDetailPage/components/Container.tsx
  src/pages/DesignerDetailPage/components/DesignerDetail.tsx
  src/pages/DesignerDetailPage/components/DesignerDetailHeader.tsx
  src/pages/DesignerListPage/components/DesignerFilter/DesignerFilterDrawer.tsx
  src/pages/DesignerListPage/components/DesignerFilter/FilterDrawer.tsx
  src/pages/DesignerListPage/index.tsx
  src/pages/MyPage/components/MyPageHeader.tsx
  src/pages/PaymentBankTransferPage/index.tsx
  src/pages/PaymentPage/index.tsx
  src/pages/ReservationPrepare/components/ReservationPrepareHeader.tsx
  src/pages/ReservationPrepare/index.tsx
  src/types/types.ts
  tailwind.config.ts
Labels: feature

#66 버그 수정 및 리펙토링
  src/pages/DesignerDetailPage/components/DesignerDetail.tsx
  src/pages/DesignerListPage/components/DesignerFilter/DesignerFilterDrawer.tsx
  src/pages/DesignerListPage/components/DesignerList/DesignerItem.tsx
  src/pages/ReservationPrepare/index.tsx
Labels: feature

#74 에러 표시 추가
  src/apis/designerList.ts
  src/apis/endpoints.ts
  src/components/ui/toast.tsx
  src/config/axiosDevConfig.ts
  src/pages/DesignerDetailPage/components/DesignerDetail.tsx
  src/pages/DesignerListPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/PaymentBankTransferPage/index.tsx
  src/pages/ReservationListPage/index.tsx
  tailwind.config.ts
Labels: bug

#76 마이페이지 리뉴얼
  src/pages/MyPage/components/DeleteUserDialog.tsx
  src/pages/MyPage/components/MyPageHeader.tsx
  src/pages/MyPage/components/ProfileInfo.tsx
  src/pages/MyPage/index.tsx
Labels: feature

#83 ENHANCE 계좌이체 에러 핸들링 로직고도화
  src/pages/LoginPage/components/LogoSection.tsx
  src/pages/LoginPage/index.tsx
  src/pages/PaymentPage/index.tsx
Labels: enhancement

#84 모바일 웹 체크용 에러 메시지 구체화
  src/components/common/LoadingSpinner.tsx
  src/pages/DesignerListPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/PaymentPage/index.tsx
  src/pages/ReservationListPage/components/ReservationList.tsx
  src/pages/ReservationListPage/index.tsx
Labels: enhancement
